export interface Movie {
    id?: string; // Optional because it's generated by Firestore
    title: string;
    tagline?: string;
    description: string;
    posterUrl: string;
    videoUrl?: string; // Trailer URL
    year: string;
    genre: string;
    duration?: string; // e.g., "2h 15m"
    featured: boolean; // If true, shows in Hero Slider
    sliderDuration?: number; // Duration in ms for this slide in the hero
    createdAt: string; // ISO string
}
